### ISSUE TITLE
sidebar-menu.scss seems missing from the npm package

### ISSUE THREAD

**Issue by hayate** [ivp-dev/react-bootstrap-sidebar-menu#1]
I am not sure if I am missing something or if this is an issue. I installed `react-bootstrap-sidebar-menu` using npm, I have react-bootstrap installed too. 
When I add the `<SideMenu>` the menu items are completely unstyled. Looking at Chrome Inspect, I don't see the `sidebar-menu.scss`.  I can see when I run inspect on your demo.

I looked inside the package folder within `node_moduels,` and I could not see any CSS there.
So is there an issue with the npm package, or have I missed something?

**Comment by hayate** [comment]
To circle back. 
To make it work I did the following:
1. clone this repo
2. from `www/styles/` take: `bootstrap-imports.scss` and `sidebar-menu.scss`
3. replace all the separate bootstrap imports with just importing the whole of boostrap (`@import "../../node_modules/bootstrap/scss/bootstrap";`
4. leave `@import "./sidebar-menu";`
5. at this stage`bootstrap-imports.scss` only contains two imports: the whole of boostrap and sitebar-menu
6. sass compile `bootstrap-imports.scss` generating: `bootstrap-imports.css`
7. In `App.js` I replaced `import 'bootstrap/dist/css/bootstrap.min.css';` with `import './styles/bootstrap-imports.css';`

Now all seems to work as it should.

Note: I am more of a backend programmer. I think something is missing in the npm package of this repo. 
And the workaround above works. (It provides the missing styles to SideMenu). 
However, it could also be that something is wrong with my environment or that I am missing something. In normal circumstances, `react-bootstrap-sidebar-menu` might works as expected after running `npm install react-bootstrap-sidebar-menu`.

**Comment by kn327** [comment]
Yep, the styling is missing from the npm package - removing from my project

**Comment by v3ss0n** [comment]
Confirmed , this is a bug 
This component is not working without scss files included in the demo.

**Comment by ivp-dev** [comment]
I add sidebar-menu.scss to the package. Now you can just import style into your stylesheet to apply styles like that (after bootstrap styles):
```
@import "react-bootstrap-sidebar-menu/dist/sidebar-menu.scss"
```

**Comment by v3ss0n** [comment]
Thanks , this lib needs more stars.

**Comment by nsanzimanagilbert** [comment]
![image](https://user-images.githubusercontent.com/38226948/200681962-91981cb4-58ea-42b9-8674-87c5d6d89e6c.png)

Did anyone account this after running `npm install react-bootstrap-sidebar-menu` and `import 'react-bootstrap-sidebar-menu/dist/sidebar-menu.scss'` ? 
How was it solved? Did I miss out something? I am really having trouble with getting the package running.

**Comment by ivp-dev** [comment]
This error means that $navbar-toggler-padding-x variable is not defined. This variable comes from bootstrap styles. You should import bootstrap styles before adding style from the lib

**Comment by Dimbles** [comment]
how do I import "bootstrap styles" ?

**Comment by ayeshaa** [comment]
> I included sidebar-menu.scss to the package. Now you can just import style into your stylesheet like that (after bootstrap styles):
> 
> ```
> @import "~react-bootstrap-sidebar-menu/dist/sidebar-menu.scss"
> ```
> 
> Please note that you should firstly import bootstrap styles

Please provide a example with code. Thanks
