### ISSUE TITLE
Cannot set width of the SidebarMenu when expanded.

### ISSUE THREAD

**Issue by khosrowkhazraei** [ivp-dev/react-bootstrap-sidebar-menu#14]
<SidebarMenu.Collapse getScrollValue={200}>, this dose not work either passing string or number as indicated by the api

**Comment by ivp-dev** [comment]
In order to adjust the width of the sidebar according to your preference, it is necessary to modify the target width in your stylesheet for the CSS class ".sidebar-menu-collapse.show." There is an example - https://codesandbox.io/s/react-bootstrap-sidebar-menu-ck23cz?file=/src/App.jsx

**Comment by khosrowkhazraei** [comment]
Then how would you use the API as described in the documentation?
The documentation is very limited, and your example does not respond to my question. You modified the default value in the $sidebar-menu-width-expanded: 500px !default; SCSS file while this file is in the library and should not be modified by users. Moreover, in the CSS file, I could not find any CSS definition to sit the width of the expanded sidebar. Even if you modify the default value in the SCSS file, it will create a transition issue, please check with sitting it to 200px instead of 500.

**Comment by ivp-dev** [comment]
For avoiding transition issues, please set the target value as "getScrollValue={200}" and apply the same size to the class "sidebar-menu-collapse.show: {width: '200px'}".

**Comment by ivp-dev** [comment]
Feel free to open issue
