### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by noobix** [ivp-dev/react-bootstrap-sidebar-menu#2]
I am  a beginner in react framework so that makes me new to JavaScript. I am trying to use an accordion menu for my hospital project and I was excited to find your component but there is an issue of documentation for me. I need to know how to create main menu and submenu and also I could not get any look and feel so if I can a component tree like what you have on this page. I know you mite not understand what I am saying but if  you can give me as a beginner exposure to you library. I found this site https://ivp-dev.github.io/react-bootstrap-sidebar-menu/ but still could not understand any thing. If you can, give little time and give me an exposure.

**Comment by v3ss0n** [comment]
This module is broken so better not use it for now , and to make it work you need to drilldown into demo source code. not recommended for beginners.
