### ISSUE TITLE
Issue importing the styles

### ISSUE THREAD

**Issue by xiomxiom** [ivp-dev/react-bootstrap-sidebar-menu#3]
ERROR in ./src/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
3 │ $sidebar-menu-toggle-padding-x: $navbar-toggler-padding-x !default;

**Comment by ivp-dev** [comment]
You probably just need to ```@import "~bootstrap/scss/bootstrap";``` (that's where $navbar-toggler-padding-x is defined) before ```@import "~react-bootstrap-sidebar-menu/dist/sidebar-menu.scss";```
