### ISSUE TITLE
Documentation for layout

### ISSUE THREAD

**Issue by redimongo** [ivp-dev/react-bootstrap-sidebar-menu#7]
So I have it working however it's not floating on top of my content and instead pushing my content down the page.

How do I give it a z-index so it sits above everything.

**Comment by ivp-dev** [comment]
Maybe there is a problem with some styles, you can check in www folder how I deal with css for main layout, it could help you to find out what is wrong with yours. In case of any questions or suggestion fell free to ask.

**Comment by redimongo** [comment]
The issue is we don't use scss we use css in NextJS. I am wondering how do we import the style into a nextjs app.

`@import '~react-bootstrap-sidebar-menu/dist/sidebar-menu.scss'`

That does not work.

**Comment by ivp-dev** [comment]
[Here](https://github.com/ivp-dev/react-bootstrap-sidebar-menu/issues/1#issuecomment-1105877586) was a discussion about how to import css style into app. It is mainly a manual work but I don't have any other option for the moment.
