### ISSUE TITLE
SCSS Compile Error

### ISSUE THREAD

**Issue by edmundsj** [ivp-dev/react-bootstrap-sidebar-menu#9]
I get the following error when trying to import `<SidebarMenu>` when importing the specified `.scss` file with:

```
import 'react-bootstrap-sidebar-menu/dist/sidebar-menu.scss';
````

```
Compiled with problems:X

ERROR in ./node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss)

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
3 │ $sidebar-menu-toggle-padding-x: $navbar-toggler-padding-x !default;
  │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss 3:33  root stylesheet
```

Inspecting the .scss file, indeed there is no `navbar-toggler-padding-x` variable. After fixing this error, it looks like there are a *lot* of undefined .scss variables. Mind putting them back in if you deleted them?

**Comment by edmundsj** [comment]
An initial (incomplete) list of the missing values, along with an initial guess for them:

```
$navbar-toggler-padding-x: 1em;
$navbar-brand-font-size: 1em;
$border-width: 1em;
$navbar-padding-y: 1em;
$navbar-padding-x: 1em;
$navbar-brand-height: 2em;
$navbar-brand-padding-y: 1em;
$navbar-brand-margin-end: 0.5em;
```

**Comment by ivp-dev** [comment]
Hi! Thank you for detailed error description. These variables shouldn't be defined in lib's scss file. It is extected that you hava imported it from bootstrap style (list of variables [here](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss)) before  using style from the lib

**Comment by edmundsj** [comment]
That's awkward... when I try to import the bootstrap variables into my own stylesheet, I *still* get a compile error. Are you sure the `_variables.scss` is intended to be imported directly? I have tried both importing `_variables.scss` above the stylesheet here using `import` statements, as well as trying to import both into my own stylesheet. I get the following error when I try to do the latter:

```
Compiled with problems:X

ERROR in ./src/components/coaching/styles/CoachingDashboard.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/components/coaching/styles/CoachingDashboard.scss)

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
    ╷
441 │ @include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap/scss/_variables.scss 441:1          @import
  src/components/coaching/styles/CoachingDashboard.scss 1:9  root stylesheet
```

Because the number of variables is so small, and bootstrap does not seem to explicitly support import of the `_variables.scss` file, I suggest they be copied and this packages' CSS be entirely self-contained.

**Comment by edmundsj** [comment]
It looks like `variables` is *not* intended to be imported on its own, it has dependencies (per [this doc](https://getbootstrap.com/docs/5.0/customize/sass/)). The following imports compile without error:

```
@import "../../../../node_modules/bootstrap/scss/functions";
@import "../../../../node_modules/bootstrap/scss/variables";
```
However, it looks like there are other dependencies in the `sidebar-menu.scss` file. I have tried the following imports, including the functions, variables, and mixins from bootstrap: 

```
@import "../../../../node_modules/bootstrap/scss/functions";
@import "../../../../node_modules/bootstrap/scss/variables";
@import "../../../../node_modules/bootstrap/scss/mixins";
@import "react-bootstrap-sidebar-menu/dist/sidebar-menu";
```

But am *still* getting a compile error:
```
Compiled with problems:X

ERROR in ./src/components/coaching/styles/CoachingDashboard.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/components/coaching/styles/CoachingDashboard.scss)

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: The target selector was not found.
Use "@extend .navbar !optional" to avoid this error.
   ╷
66 │   @extend .navbar;
   │   ^^^^^^^^^^^^^^^
   ╵
  node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss 66:3  root stylesheet
```
How do I know where to find the `.navbar` mixin, if it's not in `bootstrap`'s `mixins` file?

**Comment by edmundsj** [comment]
Ok, phew, I was able to figure out all the dependencies:

```
@import "../../../../node_modules/bootstrap/scss/functions";
@import "../../../../node_modules/bootstrap/scss/variables";
@import "../../../../node_modules/bootstrap/scss/mixins";
@import "../../../../node_modules/bootstrap/scss/navbar";
@import "../../../../node_modules/bootstrap/scss/nav";
@import "../../../../node_modules/bootstrap/scss/accordion";
@import "react-bootstrap-sidebar-menu/dist/sidebar-menu";
```
Importing all of these causes my stylesheet to be compiled without error.

**Comment by ivp-dev** [comment]
There is an example in the package where you can find all [necessary imports](https://github.com/ivp-dev/react-bootstrap-sidebar-menu/blob/main/www/src/styles/bootstrap-imports.scss) from bootstrap

**Comment by ivp-dev** [comment]
Or you can import all bootstrap styles like [here](https://react-bootstrap.github.io/getting-started/introduction/#sass)

**Comment by edmundsj** [comment]
Yup, that worked, the following compiled without error:

```
@import "../../../../node_modules/bootstrap/scss/bootstrap";
@import "react-bootstrap-sidebar-menu/dist/sidebar-menu";
```

**Comment by ivp-dev** [comment]
try to simplify your import like that `@import "~bootstrap/scss/bootstrap";`

**Comment by rotirotirafa** [comment]
i cant import using NextJS.. 

error:

`./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[1].oneOf[12].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[1].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[12].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[1].oneOf[12].use[4]!./node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss
SassError: Undefined variable.
  ╷
3 │ $sidebar-menu-toggle-padding-x: $navbar-toggler-padding-x !default;
  │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\react-bootstrap-sidebar-menu\dist\sidebar-menu.scss 3:33  root stylesheet

Import trace for requested module:
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[1].oneOf[12].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[1].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[12].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[1].oneOf[12].use[4]!./node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss
./node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss`

**Comment by ivp-dev** [comment]
please take a look into example https://codesandbox.io/s/react-bootstrap-sidebar-menu-ck23cz?file=/src/App.jsx, and try to use style from there

**Comment by Norlandz** [comment]
> There is an example in the package where you can find all [necessary imports](https://github.com/ivp-dev/react-bootstrap-sidebar-menu/blob/main/www/src/styles/bootstrap-imports.scss) from bootstrap

(that helped me out)

#### a working ex (in my case)
`H:\Using\TLightChat\tlightchat-main\src\scss`
```scss
// https://ivp-dev.github.io/react-bootstrap-sidebar-menu/
// https://getbootstrap.com/docs/5.0/customize/sass/#importing
// Custom.scss
// Option B: Include parts of Bootstrap

// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "../../node_modules/bootstrap/scss/functions";

// 2. Include any default variable overrides here

// 3. Include remainder of required Bootstrap stylesheets
@import "../../node_modules/bootstrap/scss/variables";
@import "../../node_modules/bootstrap/scss/mixins";

// https://stackoverflow.com/questions/73400844/undefined-variable-theme-colors-rgb-in-bootstrap-root-scss
@import '../../node_modules/bootstrap/scss/variables-dark';
@import '../../node_modules/bootstrap/scss/maps';
@import '../../node_modules/bootstrap/scss/utilities';

// 4. Include any optional Bootstrap components as you like
@import "../../node_modules/bootstrap/scss/root";
@import "../../node_modules/bootstrap/scss/reboot";
@import "../../node_modules/bootstrap/scss/type";
@import "../../node_modules/bootstrap/scss/images";
@import "../../node_modules/bootstrap/scss/containers";
@import "../../node_modules/bootstrap/scss/grid";

// 5. Add additional custom code here

.....

// https://github.com/ivp-dev/react-bootstrap-sidebar-menu/issues/9
@import "../../node_modules/bootstrap/scss/bootstrap";

// @import "react-bootstrap-sidebar-menu/src";
@import "../../node_modules/react-bootstrap-sidebar-menu/dist/sidebar-menu.scss";
```

`H:\Using\TLightChat\tlightchat-main\src\App.tsx`
```
// ;wrong not_here; import 'bootstrap/dist/css/bootstrap.css';
import './scss/custom.scss';
// ;wrong not_here; import 'react-bootstrap-sidebar-menu/dist/sidebar-menu.scss';
```



#### some resource to look at
```
https://getbootstrap.com/docs/5.0/customize/sass/#importing
https://stackoverflow.com/questions/73400844/undefined-variable-theme-colors-rgb-in-bootstrap-root-scss
https://github.com/ivp-dev/react-bootstrap-sidebar-menu/issues/9 (this)
```
